name: jebl3 tests
on: [ push, pull_request, workflow_dispatch ]

jobs:
  test-jebl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'gradle'
      - name: Run Gradle build
        # no test yet
        run: ./gradlew build
